### ISSUE TITLE
getting unknown on two sensors

### ISSUE THREAD

**Issue by snigehere** [jampez77/DVLA-Vehicle-Enquiry-Service#20]
Following install of 2024.9.2 I have two sensors not populating .. I see in the change log some work on these "Also updated sensor / binary_sensor code to better update once added" 

entity_id: binary_sensor.dvla_<reg#>_motstatus 
state: unknown
entity_id: binary_sensor.dvla_<reg#>_taxstatus 
state: unknown

Not sure if they relate to these sensors?
sensor.dvla_<reg#>_motstatus
sensor.dvla_<reg#>_taxstatus

when I check properties both show as still being updated by the integration so I am not able to delete the binary_sensor

**Comment by snigehere** [comment]
Thanks for the fast fix.. installed without any issues and all good again.

**Comment by nivek1612** [comment]
Prior to this update when a vehicle is not due an MOT the MOT due date was set to Null rather than not returned as that makes HA give this error. "This entity is no longer being provided by the dvla integration. If the entity is no longer in use, delete it in settings" Can we go back to that setting?
