### ISSUE TITLE
Should the binary_sensor be On or Off ?

### ISSUE THREAD

**Issue by godfreym29** [jampez77/DVLA-Vehicle-Enquiry-Service#22]
Thanks for the integration

A query?
Both of my binary sensors 'binary_sensor.dvla_xxxxxxx_motstatus' & 'binary_sensor.dvla_xxxxxxx_taxstatus' are showing as Off.

Before the recent updates they showed as On.

The car is taxed & MOT'd
The MOT Status is showing as Valid and the Tax Status is showing as Taxed

I've tried removing the integration from HACS and re-downloading it, etc, but they remain in the Off state.

I don't have any errors in the logs except for:
``
Detected that custom integration 'dvla' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/dvla/sensor.py, line 137: self.hass.async_add_job(self.async_remove()), please create a bug report at https://github.com/jampez77/DVLA-Vehicle-Enquiry-Service/issues
``
which I don't think is relevant.

Any suggestions?

**Comment by jampez77** [comment]
Thanks for bringing this to my attention, I will look into this one I return from my holidays

**Comment by hughsaunders** [comment]
I've noticed the same thing, I suspect this is related to 9f336a7e833530fd5e3c9d0e883c09f0f63ebe44, because update from cordinator sets [self._state](https://github.com/jampez77/DVLA-Vehicle-Enquiry-Service/commit/9f336a7e833530fd5e3c9d0e883c09f0f63ebe44#diff-c4385f3c5d99bb6f87dc30f805b8cc1010f7048308c6a1f2635b517cae102784R125), but is_on reads [self._attr_is_on](https://github.com/jampez77/DVLA-Vehicle-Enquiry-Service/commit/9f336a7e833530fd5e3c9d0e883c09f0f63ebe44#diff-94cd19e18e414ad629cc1b1fb7230d21a290c452a9f656c3758a0ffca7ce97e1R124)

**Comment by snigehere** [comment]
Hope you are having a restful holiday ... you are far too dedicated replying while you are on holiday!! 

I see the same thing
sensor.dvla_<reg>_motstatus shows as "Valid"

binary_sensor.dvla_<reg>_motstatus is "off" however the sensor friendly name is "MOT Valid" so I would have expected it to be "on" as opposed to "off"

**Comment by jampez77** [comment]
> Hope you are having a restful holiday ... you are far too dedicated replying while you are on holiday!!
Thanks, i had a lovely time and most importantly the children loved it :)

**Comment by jampez77** [comment]
This should be fixed now with [2024.9.4](/https://github.com/jampez77/DVLA-Vehicle-Enquiry-Service/releases/tag/2024.9.4)

**Comment by godfreym29** [comment]
I've applied the latest release
and it's all working again,

Thank you

**Comment by jampez77** [comment]
Excellent news, thanks!
